/* generated by tools/build_elf_page.py - do not edit */
window.PAYLOAD_TILES = [
    { title: "etaHEN", description: "Homebrew enabler and payload host.", name: "etaHEN.elf", key: "etahen" },
    { title: "ps5-kstuff", description: "Kernel support payload and FPKG enabler.", name: "kstuff.elf", key: "kstuff" },
    { title: "ftpsrv", description: "FTP server. Runs on port 2121.", name: "ftpsrv-ps5.elf", key: "ftp" },
    { title: "websrv", description: "Homebrew web server. Runs on port 8080.", name: "websrv-ps5.elf", key: "web" },
    { title: "PLK Manager v0.5.2 (13.60)", description: "Rebuilt with latest SDK. Open PS5-IP:8084.", name: "pldmgr_v0.5.2.elf", key: "pldmgr-v052", art: false },
    { title: "nanodns", description: "nanodns payload.", name: "nanodns.elf", key: "nanodns", art: false },
    { title: "shadowmountplus", description: "shadowmountplus payload.", name: "shadowmountplus.elf", key: "shadowmountplus", art: false },
    { title: "Game Compressor 1.0.4 · 13.60", description: "Relapse PS5 SDK build. Opens port 5910.", name: "game-compressor.elf", key: "game-compressor", art: false },
    { title: "CheatRunner v0.17", description: "Local cheat dashboard. Opens port 9999.", name: "CheatRunner.elf", key: "cheatrunner", art: false }
];
window.PAYLOAD_ART = { dir: "ui/", pfx: "btn-", on: true };
